// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#ifndef _PYPILOT_UI_H
#define _PYPILOT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen2.h"
#include "ui_Screen1.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * flashWifi_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo300x300_png);    // assets/logo300x300.png
LV_IMG_DECLARE(ui_img_compass_png);    // assets/compass.png
LV_IMG_DECLARE(ui_img_green_png);    // assets/green.png
LV_IMG_DECLARE(ui_img_red_png);    // assets/red.png
LV_IMG_DECLARE(ui_img_fade_png);    // assets/fade.png
LV_IMG_DECLARE(ui_img_indicator_png);    // assets/indicator.png
LV_IMG_DECLARE(ui_img_degrees_png);    // assets/degrees.png
LV_IMG_DECLARE(ui_img_wheel_png);    // assets/wheel.png
LV_IMG_DECLARE(ui_img_rudderline_png);    // assets/RudderLine.png
LV_IMG_DECLARE(ui_img_rudder_png);    // assets/rudder.png
LV_IMG_DECLARE(ui_img_wifigreen_png);    // assets/wifiGreen.png
LV_IMG_DECLARE(ui_img_wifiyellow_png);    // assets/wifiYellow.png
LV_IMG_DECLARE(ui_img_wifired_png);    // assets/wifiRed.png
LV_IMG_DECLARE(ui_img_degreesinv_png);    // assets/degreesINV.png
LV_IMG_DECLARE(ui_img_fadeinv_png);    // assets/fadeINV.png
LV_IMG_DECLARE(ui_img_indicatorinv_png);    // assets/indicatorINV.png
LV_IMG_DECLARE(ui_img_rudderinv_png);    // assets/rudderINV.png
LV_IMG_DECLARE(ui_img_compassinv_png);    // assets/compassINV.png
LV_IMG_DECLARE(ui_img_wheelinv_png);    // assets/wheelINV.png
LV_IMG_DECLARE(ui_img_rudderlineinv_png);    // assets/RudderLineINV.png
LV_IMG_DECLARE(ui_img_redinv_png);    // assets/redINV.png
LV_IMG_DECLARE(ui_img_greeninv_png);    // assets/greenINV.png

// FONTS
LV_FONT_DECLARE(ui_font_whitrabt100);
LV_FONT_DECLARE(ui_font_whitrabt12);
LV_FONT_DECLARE(ui_font_whitrabt16);
LV_FONT_DECLARE(ui_font_whitrbt20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
