// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_motorVoltage;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_motorCurrent;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Container30;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_motorWatts;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_motorAh;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Container32;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_motorMaxC;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_motorTemp;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Container34;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_driverTemp;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_compCal;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_accCal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

