// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#include "ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_scroll = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_debugLog = NULL;
// event funtions

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_Screen5, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scroll = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_scroll);
    lv_obj_set_width(ui_scroll, 300);
    lv_obj_set_height(ui_scroll, 200);
    lv_obj_set_align(ui_scroll, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_scroll, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_scroll, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_scroll, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_scroll, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_scroll, LV_DIR_VER);

    ui_Label10 = lv_label_create(ui_scroll);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -2);
    lv_obj_set_y(ui_Label10, -109);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Serial Output:");
    lv_obj_clear_flag(ui_Label10, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_whitrabt12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugLog = lv_label_create(ui_scroll);
    lv_obj_set_width(ui_debugLog, 295);
    lv_obj_set_height(ui_debugLog, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_debugLog, 4);
    lv_obj_set_y(ui_debugLog, -92);
    lv_obj_set_align(ui_debugLog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_debugLog, "");
    lv_obj_add_flag(ui_debugLog, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_debugLog, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_debugLog, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_debugLog, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_debugLog, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_debugLog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_debugLog, &ui_font_whitrabt12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_debugLog, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_debugLog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_debugLog, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_debugLog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_scroll = NULL;
    ui_Label10 = NULL;
    ui_debugLog = NULL;

}
