// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Container29 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_motorVoltage = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_Container28 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_motorCurrent = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Container30 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_motorWatts = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_Container31 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_motorAh = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_Container32 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_motorMaxC = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_Container33 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_motorTemp = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Container34 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_driverTemp = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_compCal = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_accCal = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label14, 108);
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -109);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Info Screen");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label14, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 320);
    lv_obj_set_height(ui_Container1, 210);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 10);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Container1, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(ui_Container1, LV_SCROLL_SNAP_START);
    lv_obj_set_style_pad_left(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container29 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container29);
    lv_obj_set_width(ui_Container29, 320);
    lv_obj_set_height(ui_Container29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container29, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container29, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container29, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container29, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Container29);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 33);
    lv_obj_set_y(ui_Label37, 19);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Motor Voltage: ");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motorVoltage = lv_label_create(ui_Container29);
    lv_obj_set_x(ui_motorVoltage, 33);
    lv_obj_set_y(ui_motorVoltage, 19);
    lv_obj_set_align(ui_motorVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_motorVoltage, "");
    lv_obj_set_style_text_color(ui_motorVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_motorVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_motorVoltage, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Container29);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Label38, 33);
    lv_obj_set_y(ui_Label38, 19);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, " Volts");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container28 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, 320);
    lv_obj_set_height(ui_Container28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container28, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container28, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container28, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Container28);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 33);
    lv_obj_set_y(ui_Label35, 19);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Motor Current: ");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motorCurrent = lv_label_create(ui_Container28);
    lv_obj_set_x(ui_motorCurrent, 33);
    lv_obj_set_y(ui_motorCurrent, 19);
    lv_obj_set_align(ui_motorCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_motorCurrent, "");
    lv_obj_set_style_text_color(ui_motorCurrent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_motorCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_motorCurrent, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Container28);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Label36, 33);
    lv_obj_set_y(ui_Label36, 19);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, " Amps");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container30 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container30);
    lv_obj_set_width(ui_Container30, 320);
    lv_obj_set_height(ui_Container30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container30, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container30, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container30, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Container30);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 33);
    lv_obj_set_y(ui_Label39, 19);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Motor Watts: ");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motorWatts = lv_label_create(ui_Container30);
    lv_obj_set_x(ui_motorWatts, 33);
    lv_obj_set_y(ui_motorWatts, 19);
    lv_obj_set_align(ui_motorWatts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_motorWatts, "");
    lv_obj_set_style_text_color(ui_motorWatts, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_motorWatts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_motorWatts, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Container30);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Label40, 33);
    lv_obj_set_y(ui_Label40, 19);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, " Watts");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container31 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container31);
    lv_obj_set_width(ui_Container31, 320);
    lv_obj_set_height(ui_Container31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container31, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container31, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container31, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container31, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Container31);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 33);
    lv_obj_set_y(ui_Label41, 19);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Motor AmpHours: ");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motorAh = lv_label_create(ui_Container31);
    lv_obj_set_x(ui_motorAh, 33);
    lv_obj_set_y(ui_motorAh, 19);
    lv_obj_set_align(ui_motorAh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_motorAh, "");
    lv_obj_set_style_text_color(ui_motorAh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_motorAh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_motorAh, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Container31);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Label42, 33);
    lv_obj_set_y(ui_Label42, 19);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, " Ah");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container32 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container32);
    lv_obj_set_width(ui_Container32, 320);
    lv_obj_set_height(ui_Container32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container32, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container32, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container32, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container32, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Container32);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 33);
    lv_obj_set_y(ui_Label43, 19);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Motor Max Current: ");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motorMaxC = lv_label_create(ui_Container32);
    lv_obj_set_x(ui_motorMaxC, 33);
    lv_obj_set_y(ui_motorMaxC, 19);
    lv_obj_set_align(ui_motorMaxC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_motorMaxC, "");
    lv_obj_set_style_text_color(ui_motorMaxC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_motorMaxC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_motorMaxC, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Container32);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Label44, 33);
    lv_obj_set_y(ui_Label44, 19);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, " Amps");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container33 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container33);
    lv_obj_set_width(ui_Container33, 320);
    lv_obj_set_height(ui_Container33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container33, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container33, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container33, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container33, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Container33);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 33);
    lv_obj_set_y(ui_Label45, 19);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "Motor Temp: ");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motorTemp = lv_label_create(ui_Container33);
    lv_obj_set_x(ui_motorTemp, 33);
    lv_obj_set_y(ui_motorTemp, 19);
    lv_obj_set_align(ui_motorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_motorTemp, "");
    lv_obj_set_style_text_color(ui_motorTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_motorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_motorTemp, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Container33);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Label46, 33);
    lv_obj_set_y(ui_Label46, 19);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, " Degrees Cels");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container34 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container34);
    lv_obj_set_width(ui_Container34, 320);
    lv_obj_set_height(ui_Container34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container34, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container34, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container34, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container34, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container34, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Container34);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 33);
    lv_obj_set_y(ui_Label47, 19);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "Driver Temp: ");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_driverTemp = lv_label_create(ui_Container34);
    lv_obj_set_x(ui_driverTemp, 33);
    lv_obj_set_y(ui_driverTemp, 19);
    lv_obj_set_align(ui_driverTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_driverTemp, "");
    lv_obj_set_style_text_color(ui_driverTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_driverTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_driverTemp, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_Container34);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Label48, 33);
    lv_obj_set_y(ui_Label48, 19);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, " Degrees Cels");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 320);
    lv_obj_set_height(ui_Container13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 33);
    lv_obj_set_y(ui_Label12, 19);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Compass Calibration: ");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_compCal = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_compCal, 190);
    lv_obj_set_height(ui_compCal, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_compCal, 33);
    lv_obj_set_y(ui_compCal, 19);
    lv_obj_set_align(ui_compCal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_compCal, "UNLOCKED");
    lv_obj_set_style_text_color(ui_compCal, lv_color_hex(0xBD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_compCal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_compCal, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 320);
    lv_obj_set_height(ui_Container14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 33);
    lv_obj_set_y(ui_Label13, 19);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Accelerom Calibration: ");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accCal = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_accCal, 190);
    lv_obj_set_height(ui_accCal, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_accCal, 33);
    lv_obj_set_y(ui_accCal, 19);
    lv_obj_set_align(ui_accCal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_accCal, "UNLOCKED");
    lv_obj_set_style_text_color(ui_accCal, lv_color_hex(0xBD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accCal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accCal, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Label14 = NULL;
    ui_Container1 = NULL;
    ui_Container29 = NULL;
    ui_Label37 = NULL;
    ui_motorVoltage = NULL;
    ui_Label38 = NULL;
    ui_Container28 = NULL;
    ui_Label35 = NULL;
    ui_motorCurrent = NULL;
    ui_Label36 = NULL;
    ui_Container30 = NULL;
    ui_Label39 = NULL;
    ui_motorWatts = NULL;
    ui_Label40 = NULL;
    ui_Container31 = NULL;
    ui_Label41 = NULL;
    ui_motorAh = NULL;
    ui_Label42 = NULL;
    ui_Container32 = NULL;
    ui_Label43 = NULL;
    ui_motorMaxC = NULL;
    ui_Label44 = NULL;
    ui_Container33 = NULL;
    ui_Label45 = NULL;
    ui_motorTemp = NULL;
    ui_Label46 = NULL;
    ui_Container34 = NULL;
    ui_Label47 = NULL;
    ui_driverTemp = NULL;
    ui_Label48 = NULL;
    ui_Container13 = NULL;
    ui_Label12 = NULL;
    ui_compCal = NULL;
    ui_Container14 = NULL;
    ui_Label13 = NULL;
    ui_accCal = NULL;

}
