// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_compassStrip;
extern lv_obj_t * ui_greengradient;
extern lv_obj_t * ui_redgradient;
extern lv_obj_t * ui_fade;
extern lv_obj_t * ui_cmd;
extern lv_obj_t * ui_indicator;
extern lv_obj_t * ui_degSymbol;
extern lv_obj_t * ui_rudderSymbol;
extern lv_obj_t * ui_rudder;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_wifiGreen;
extern lv_obj_t * ui_wifiYellow;
extern lv_obj_t * ui_wifiRed;
extern lv_obj_t * ui_activeMode;
extern lv_obj_t * ui_engaged;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Bar2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

