// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_wifiMsg;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ssid;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_IPadress;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_profile;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_pypilotVersion;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_imuWarning;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_servoFlags;
extern lv_obj_t * ui_SPACE;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_sourceGps;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_sourceWind;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_sourceTruewind;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_sourceRudder;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_sourceApb;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_sourceWater;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

