// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_wifiMsg = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_ssid = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_IPadress = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_profile = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_pypilotVersion = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_imuWarning = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_servoFlags = NULL;
lv_obj_t * ui_SPACE = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_sourceGps = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_sourceWind = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_sourceTruewind = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_sourceRudder = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_sourceApb = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_sourceWater = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label1, 108);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -109);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Info Screen");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, 210);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 10);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scrollbar_mode(ui_Container2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Container2, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(ui_Container2, LV_SCROLL_SNAP_START);
    lv_obj_set_style_pad_left(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 320);
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 33);
    lv_obj_set_y(ui_Label2, 19);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Wifi: ");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiMsg = lv_label_create(ui_Container3);
    lv_obj_set_height(ui_wifiMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_wifiMsg, 1);
    lv_obj_set_x(ui_wifiMsg, 33);
    lv_obj_set_y(ui_wifiMsg, 19);
    lv_obj_set_align(ui_wifiMsg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiMsg, "");
    lv_obj_set_style_text_color(ui_wifiMsg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiMsg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiMsg, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 320);
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 33);
    lv_obj_set_y(ui_Label4, 19);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SSID: ");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssid = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_ssid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssid, 33);
    lv_obj_set_y(ui_ssid, 19);
    lv_obj_set_align(ui_ssid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssid, "");
    lv_obj_set_style_text_color(ui_ssid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssid, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 320);
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 33);
    lv_obj_set_y(ui_Label5, 19);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "IP: ");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPadress = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_IPadress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPadress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPadress, 33);
    lv_obj_set_y(ui_IPadress, 19);
    lv_obj_set_align(ui_IPadress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPadress, "");
    lv_obj_set_style_text_color(ui_IPadress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPadress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPadress, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 320);
    lv_obj_set_height(ui_Container5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 33);
    lv_obj_set_y(ui_Label9, 19);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Profile: ");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_profile = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_profile, 190);
    lv_obj_set_height(ui_profile, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_profile, 33);
    lv_obj_set_y(ui_profile, 19);
    lv_obj_set_align(ui_profile, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profile, "");
    lv_obj_set_style_text_color(ui_profile, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_profile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_profile, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 320);
    lv_obj_set_height(ui_Container7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 33);
    lv_obj_set_y(ui_Label6, 19);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Pypilot version: ");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pypilotVersion = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_pypilotVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pypilotVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pypilotVersion, 33);
    lv_obj_set_y(ui_pypilotVersion, 19);
    lv_obj_set_align(ui_pypilotVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pypilotVersion, "");
    lv_obj_set_style_text_color(ui_pypilotVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pypilotVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pypilotVersion, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 320);
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 33);
    lv_obj_set_y(ui_Label7, 19);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "IMU warning: ");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imuWarning = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_imuWarning, 190);
    lv_obj_set_height(ui_imuWarning, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_imuWarning, 33);
    lv_obj_set_y(ui_imuWarning, 19);
    lv_obj_set_align(ui_imuWarning, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_imuWarning, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_imuWarning, "");
    lv_obj_set_style_text_color(ui_imuWarning, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_imuWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_imuWarning, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 320);
    lv_obj_set_height(ui_Container9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 33);
    lv_obj_set_y(ui_Label8, 19);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Servo flags: ");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servoFlags = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_servoFlags, 190);
    lv_obj_set_height(ui_servoFlags, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_servoFlags, 33);
    lv_obj_set_y(ui_servoFlags, 19);
    lv_obj_set_align(ui_servoFlags, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_servoFlags, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_servoFlags, "");
    lv_obj_set_style_text_color(ui_servoFlags, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_servoFlags, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_servoFlags, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPACE = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_SPACE);
    lv_obj_set_width(ui_SPACE, 320);
    lv_obj_set_height(ui_SPACE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SPACE, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SPACE, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SPACE, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SPACE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SPACE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SPACE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SPACE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SPACE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_SPACE);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 33);
    lv_obj_set_y(ui_Label19, 19);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 320);
    lv_obj_set_height(ui_Container10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 33);
    lv_obj_set_y(ui_Label3, 19);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "gps.source: ");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sourceGps = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_sourceGps, 190);
    lv_obj_set_height(ui_sourceGps, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_sourceGps, 33);
    lv_obj_set_y(ui_sourceGps, 19);
    lv_obj_set_align(ui_sourceGps, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_sourceGps, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_sourceGps, "");
    lv_obj_set_style_text_color(ui_sourceGps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sourceGps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sourceGps, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 320);
    lv_obj_set_height(ui_Container11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 33);
    lv_obj_set_y(ui_Label11, 19);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "wind.source: ");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sourceWind = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_sourceWind, 190);
    lv_obj_set_height(ui_sourceWind, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_sourceWind, 33);
    lv_obj_set_y(ui_sourceWind, 19);
    lv_obj_set_align(ui_sourceWind, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_sourceWind, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_sourceWind, "");
    lv_obj_set_style_text_color(ui_sourceWind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sourceWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sourceWind, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 320);
    lv_obj_set_height(ui_Container12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 33);
    lv_obj_set_y(ui_Label15, 19);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "truewind.source: ");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sourceTruewind = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_sourceTruewind, 190);
    lv_obj_set_height(ui_sourceTruewind, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_sourceTruewind, 33);
    lv_obj_set_y(ui_sourceTruewind, 19);
    lv_obj_set_align(ui_sourceTruewind, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_sourceTruewind, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_sourceTruewind, "");
    lv_obj_set_style_text_color(ui_sourceTruewind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sourceTruewind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sourceTruewind, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 320);
    lv_obj_set_height(ui_Container15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container15, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 33);
    lv_obj_set_y(ui_Label16, 19);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "rudder.source: ");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sourceRudder = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_sourceRudder, 190);
    lv_obj_set_height(ui_sourceRudder, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_sourceRudder, 33);
    lv_obj_set_y(ui_sourceRudder, 19);
    lv_obj_set_align(ui_sourceRudder, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_sourceRudder, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_sourceRudder, "");
    lv_obj_set_style_text_color(ui_sourceRudder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sourceRudder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sourceRudder, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 320);
    lv_obj_set_height(ui_Container16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 33);
    lv_obj_set_y(ui_Label17, 19);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "apb.source: ");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sourceApb = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_sourceApb, 190);
    lv_obj_set_height(ui_sourceApb, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_sourceApb, 33);
    lv_obj_set_y(ui_sourceApb, 19);
    lv_obj_set_align(ui_sourceApb, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_sourceApb, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_sourceApb, "");
    lv_obj_set_style_text_color(ui_sourceApb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sourceApb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sourceApb, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 320);
    lv_obj_set_height(ui_Container17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container17, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 33);
    lv_obj_set_y(ui_Label18, 19);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "water.source: ");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sourceWater = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_sourceWater, 190);
    lv_obj_set_height(ui_sourceWater, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_sourceWater, 33);
    lv_obj_set_y(ui_sourceWater, 19);
    lv_obj_set_align(ui_sourceWater, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_sourceWater, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_sourceWater, "");
    lv_obj_set_style_text_color(ui_sourceWater, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sourceWater, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sourceWater, &ui_font_whitrabt16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label1 = NULL;
    ui_Container2 = NULL;
    ui_Container3 = NULL;
    ui_Label2 = NULL;
    ui_wifiMsg = NULL;
    ui_Container4 = NULL;
    ui_Label4 = NULL;
    ui_ssid = NULL;
    ui_Container6 = NULL;
    ui_Label5 = NULL;
    ui_IPadress = NULL;
    ui_Container5 = NULL;
    ui_Label9 = NULL;
    ui_profile = NULL;
    ui_Container7 = NULL;
    ui_Label6 = NULL;
    ui_pypilotVersion = NULL;
    ui_Container8 = NULL;
    ui_Label7 = NULL;
    ui_imuWarning = NULL;
    ui_Container9 = NULL;
    ui_Label8 = NULL;
    ui_servoFlags = NULL;
    ui_SPACE = NULL;
    ui_Label19 = NULL;
    ui_Container10 = NULL;
    ui_Label3 = NULL;
    ui_sourceGps = NULL;
    ui_Container11 = NULL;
    ui_Label11 = NULL;
    ui_sourceWind = NULL;
    ui_Container12 = NULL;
    ui_Label15 = NULL;
    ui_sourceTruewind = NULL;
    ui_Container15 = NULL;
    ui_Label16 = NULL;
    ui_sourceRudder = NULL;
    ui_Container16 = NULL;
    ui_Label17 = NULL;
    ui_sourceApb = NULL;
    ui_Container17 = NULL;
    ui_Label18 = NULL;
    ui_sourceWater = NULL;

}
