// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: pypilot

#include "ui.h"

lv_obj_t * uic_Bar2;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_compassStrip = NULL;
lv_obj_t * ui_greengradient = NULL;
lv_obj_t * ui_redgradient = NULL;
lv_obj_t * ui_fade = NULL;
lv_obj_t * ui_cmd = NULL;
lv_obj_t * ui_indicator = NULL;
lv_obj_t * ui_degSymbol = NULL;
lv_obj_t * ui_rudderSymbol = NULL;
lv_obj_t * ui_rudder = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_wifiGreen = NULL;
lv_obj_t * ui_wifiYellow = NULL;
lv_obj_t * ui_wifiRed = NULL;
lv_obj_t * ui_activeMode = NULL;
lv_obj_t * ui_engaged = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_compassStrip = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_compassStrip, &ui_img_compass_png);
    lv_obj_set_width(ui_compassStrip, LV_SIZE_CONTENT);   /// 1200
    lv_obj_set_height(ui_compassStrip, LV_SIZE_CONTENT);    /// 103
    lv_obj_set_x(ui_compassStrip, 0);
    lv_obj_set_y(ui_compassStrip, -95);
    lv_obj_set_align(ui_compassStrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_compassStrip, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_compassStrip, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_greengradient = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_greengradient, &ui_img_green_png);
    lv_obj_set_width(ui_greengradient, LV_SIZE_CONTENT);   /// 110
    lv_obj_set_height(ui_greengradient, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_greengradient, 110);
    lv_obj_set_y(ui_greengradient, -95);
    lv_obj_set_align(ui_greengradient, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_greengradient, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_greengradient, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redgradient = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_redgradient, &ui_img_red_png);
    lv_obj_set_width(ui_redgradient, LV_SIZE_CONTENT);   /// 110
    lv_obj_set_height(ui_redgradient, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_redgradient, -110);
    lv_obj_set_y(ui_redgradient, -95);
    lv_obj_set_align(ui_redgradient, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redgradient, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redgradient, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fade = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fade, &ui_img_fade_png);
    lv_obj_set_width(ui_fade, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_fade, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_fade, 0);
    lv_obj_set_y(ui_fade, -95);
    lv_obj_set_align(ui_fade, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fade, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fade, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cmd = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_cmd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cmd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cmd, 0);
    lv_obj_set_y(ui_cmd, 21);
    lv_obj_set_align(ui_cmd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cmd, "030");
    lv_obj_set_style_text_font(ui_cmd, &ui_font_whitrabt100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_indicator, &ui_img_indicator_png);
    lv_obj_set_width(ui_indicator, LV_SIZE_CONTENT);   /// 62
    lv_obj_set_height(ui_indicator, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_indicator, 0);
    lv_obj_set_y(ui_indicator, -80);
    lv_obj_set_align(ui_indicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_degSymbol = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_degSymbol, &ui_img_degrees_png);
    lv_obj_set_width(ui_degSymbol, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_degSymbol, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_degSymbol, 107);
    lv_obj_set_y(ui_degSymbol, -19);
    lv_obj_set_align(ui_degSymbol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_degSymbol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_degSymbol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rudderSymbol = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_rudderSymbol, &ui_img_wheel_png);
    lv_obj_set_width(ui_rudderSymbol, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_rudderSymbol, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_rudderSymbol, 0);
    lv_obj_set_y(ui_rudderSymbol, 98);
    lv_obj_set_align(ui_rudderSymbol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rudderSymbol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rudderSymbol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rudder = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_rudder, -150, 150);
    lv_slider_set_mode(ui_rudder, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_rudder, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_rudder) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_rudder, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_rudder, 447);
    lv_obj_set_height(ui_rudder, 10);
    lv_obj_set_x(ui_rudder, 0);
    lv_obj_set_y(ui_rudder, 130);
    lv_obj_set_align(ui_rudder, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_rudder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rudder, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_rudder, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rudder, lv_color_hex(0xBD0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rudder, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rudder, lv_color_hex(0x00BD3C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rudder, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_rudder, &ui_img_rudderline_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_Bar2, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_Bar2, -100, 100);
    lv_bar_set_value(ui_Bar2, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 460);
    lv_obj_set_height(ui_Bar2, 20);
    lv_obj_set_x(ui_Bar2, 0);
    lv_obj_set_y(ui_Bar2, 130);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar2, &ui_img_rudder_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_wifiGreen = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wifiGreen, &ui_img_wifigreen_png);
    lv_obj_set_width(ui_wifiGreen, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_wifiGreen, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_wifiGreen, -160);
    lv_obj_set_y(ui_wifiGreen, 12);
    lv_obj_set_align(ui_wifiGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiGreen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiYellow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wifiYellow, &ui_img_wifiyellow_png);
    lv_obj_set_width(ui_wifiYellow, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_wifiYellow, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_wifiYellow, -160);
    lv_obj_set_y(ui_wifiYellow, 12);
    lv_obj_set_align(ui_wifiYellow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiYellow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiYellow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiRed = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wifiRed, &ui_img_wifired_png);
    lv_obj_set_width(ui_wifiRed, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_wifiRed, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_wifiRed, -160);
    lv_obj_set_y(ui_wifiRed, 12);
    lv_obj_set_align(ui_wifiRed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiRed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_activeMode = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_activeMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_activeMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_activeMode, 19);
    lv_obj_set_y(ui_activeMode, 106);
    lv_obj_set_align(ui_activeMode, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_activeMode, "Navigation");
    lv_obj_set_style_text_color(ui_activeMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_activeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_activeMode, &ui_font_whitrbt20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_engaged = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_engaged, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_engaged, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_engaged, 151);
    lv_obj_set_y(ui_engaged, 21);
    lv_obj_set_align(ui_engaged, LV_ALIGN_CENTER);
    lv_label_set_text(ui_engaged, "AUTO");
    lv_obj_set_style_text_color(ui_engaged, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_engaged, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_engaged, &ui_font_whitrbt20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_engaged, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_engaged, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_engaged, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_engaged, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_engaged, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_engaged, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_engaged, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_engaged, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_engaged, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Bar2 = ui_Bar2;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_compassStrip = NULL;
    ui_greengradient = NULL;
    ui_redgradient = NULL;
    ui_fade = NULL;
    ui_cmd = NULL;
    ui_indicator = NULL;
    ui_degSymbol = NULL;
    ui_rudderSymbol = NULL;
    ui_rudder = NULL;
    uic_Bar2 = NULL;
    ui_Bar2 = NULL;
    ui_wifiGreen = NULL;
    ui_wifiYellow = NULL;
    ui_wifiRed = NULL;
    ui_activeMode = NULL;
    ui_engaged = NULL;

}
